export {
  googleCalendarActions,
  googleCalendarApiBaseUrl,
  googleCalendarCreateEventAction,
  googleCalendarDeleteEventAction,
  googleCalendarGetEventAction,
  googleCalendarListAccountsAction,
  googleCalendarListCalendarsAction,
  googleCalendarListEventsAction,
  googleCalendarUpdateEventAction,
  GoogleCalendarCreateEventInput,
  GoogleCalendarEvent,
  GoogleCalendarEventDateTime,
  GoogleCalendarEventIdInput,
  GoogleCalendarListCalendarsInput,
  GoogleCalendarListCalendarsOutput,
  GoogleCalendarListEventsInput,
  GoogleCalendarListEventsOutput,
  GoogleCalendarRef,
  GoogleCalendarUpdateEventInput
} from './calendar.ts'
export {
  googleDriveActions,
  googleDriveApiBaseUrl,
  googleDriveCreateFolderAction,
  GoogleDriveCapabilities,
  GoogleDriveContentRestriction,
  GoogleDriveCreateFolderInput,
  googleDriveDeleteFileAction,
  GoogleDriveDeleteFileOutput,
  GoogleDriveFile,
  googleDriveFileFields,
  GoogleDriveFileIdInput,
  googleDriveFolderMimeType,
  googleDriveGetFileAction,
  GoogleDriveLinkShareMetadata,
  GoogleDriveListFilesInput,
  GoogleDriveListFilesOutput,
  googleDriveListFilesAction,
  GoogleDriveSearchFilesInput,
  googleDriveSearchFilesAction,
  GoogleDriveShortcutDetails,
  googleDriveTrashFileAction,
  GoogleDriveUser
} from './drive.ts'
export {
  gmailActions,
  gmailDraftComposeAction,
  GmailDraftComposeInput,
  gmailDraftDeleteAction,
  GmailDraftIdInput,
  gmailDraftReplyAction,
  GmailDraftReplyInput,
  gmailDraftUpdateAction,
  GmailDraftUpdateInput,
  GmailAttachmentBase64,
  GmailAttachmentBase64Url,
  gmailGetAttachmentAction,
  GmailGetAttachmentInput,
  GmailGetAttachmentOutput,
  gmailGetMessageAction,
  GmailGetMessageInput,
  gmailGetThreadAction,
  GmailGetThreadInput,
  GmailListAttachmentsInput,
  GmailListAttachmentsOutput,
  gmailListAttachmentsAction,
  GmailThreadAttachment,
  GmailThreadMessage,
  GmailThreadOutput,
  GmailListInput,
  gmailListAccountsAction,
  gmailListAction,
  gmailListDraftsAction,
  gmailListLabelsAction,
  gmailListSendAsAction,
  GmailListSendAsOutput,
  GmailMessageIdInput,
  gmailSearchAction,
  gmailModifyLabelsAction,
  GmailModifyLabelsInput,
  GmailMessageOutput,
  GmailMessageRef,
  GmailSearchInput,
  GmailSearchOutput,
  GmailSendAs,
  gmailTrashAction,
  gmailUntrashAction,
  googleGmailApiBaseUrl
} from './gmail.ts'
export {
  GoogleCalendarEventsOAuthCredentialSlot,
  googleCalendarEventsScopes,
  GoogleOAuthCredentialSlot,
  GoogleCalendarReadonlyOAuthCredentialSlot,
  googleCalendarReadonlyScopes,
  GoogleCombinedOAuthCredentialSlot,
  googleAuthorizationHeaders,
  googleCalendarEventsScope,
  googleCalendarReadonlyScope,
  googleConnectorId,
  GoogleDriveFileOAuthCredentialSlot,
  googleDriveFileScope,
  googleDriveFileScopes,
  GoogleDriveMetadataReadonlyOAuthCredentialSlot,
  googleDriveMetadataReadonlyScope,
  googleDriveMetadataReadonlyScopes,
  GoogleGmailComposeOAuthCredentialSlot,
  googleGmailComposeScope,
  googleGmailComposeScopes,
  GoogleGmailDraftReplyOAuthCredentialSlot,
  googleGmailDraftReplyScopes,
  GoogleGmailModifyOAuthCredentialSlot,
  googleGmailModifyScope,
  googleGmailModifyScopes,
  GoogleGmailReadonlyOAuthCredentialSlot,
  googleGmailReadonlyScope,
  googleGmailReadonlyScopes,
  googleGmailSendScope,
  GoogleGmailSettingsOAuthCredentialSlot,
  googleGmailSettingsBasicScope,
  googleGmailSettingsScopes,
  googleOAuthAuthorizeUrl,
  googleOAuthSlotId,
  googleOAuthTokenUrl
} from './oauth.ts'
export { resolveGoogleAccessToken } from './shared.ts'

import { defineConnector } from '../connector.ts'
import { googleCalendarActions } from './calendar.ts'
import { googleDriveActions } from './drive.ts'
import { gmailActions } from './gmail.ts'
import { googleConnectorId } from './oauth.ts'

export const GoogleConnector = defineConnector({
  id: googleConnectorId,
  description: 'Google Gmail, Calendar, and Drive connector actions.',
  actions: [...gmailActions, ...googleCalendarActions, ...googleDriveActions]
})
